name: Continuous Integration Workflow

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - frontend/**
      - .github/workflows/**

jobs:
  Get-Hub-Repo:
    runs-on: ubuntu-latest
    outputs:
      hubname: ${{ steps.get-user.outputs.username }}
    steps:
      - id: get-user
        run: echo "username=$DOCKERHUBUSERNAME" >> "$GITHUB_OUTPUT"

  build_FE:
    name: Build Frontend Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install deps
        run: |
          cd frontend && npm i
          npm install -g @angular/cli

      - name: Compile code
        run: cd frontend && ng build

      - name: Unit Test
        run: cd frontend && ng test --no-watch --no-progress --browsers=ChromeHeadless

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - env:
          DOCKERHUBUSERNAME: ${{ needs.Get-Hub-Repo.outputs.hubname }}
        run: |
          env
          echo $DOCKERHUBUSERNAME
          echo $DOCKERHUB_USERNAME

      - name: Build
        env:
          USERNAME: ${{ needs.Get-Hub-Repo.outputs.hubname }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile
          tags: $USERNAME/angular-FE:latest

  # build_BE:
  #   name: Build backend Artifacts
  #   runs-on: ubuntu-latest
